### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by NioDeBacker** [HOGENT-IT-Lab/visualgo#1]
Misschien een idee om de Readme wat beter uit te werken zodat mensen die het project willen gebruiken weten wat ze moeten doen om het op te zetten?

**Comment by thomaslouage** [comment]
Heb wat verduidelijking gezet bij de Readme

**Comment by NioDeBacker** [comment]
Ik bedoel echt welke commando's om het te runnen, welke belangrijke functies, welke algoritmes al geïmplementeerd zijn,...
