### ISSUE TITLE
Gebruik yarn en npm

### ISSUE THREAD

**Issue by NioDeBacker** [HOGENT-IT-Lab/visualgo#2]
Klopt het dat jullie zowel yarn als npm aan het gebruiken zijn? Pas op hiermee want kan voor conlficts zorgen!

**Comment by thomaslouage** [comment]
Ik kan niet direct terugvinden waar je dit zou kunnen zien. Ik kan me ook enkel herinneren dat ik yarn heb gebruikt voor de packages...

**Comment by NioDeBacker** [comment]
Er is een yarn.lock én een package.lock aanwezig wat meestal wijst op het gebruik van beide.

**Comment by thomaslouage** [comment]
Ik heb de zaken betreffende npm proberen weg te werken. Ik denk dat het nu is opgelost.

**Comment by NioDeBacker** [comment]
Oke top! (btw je kan in je commits bepaalde issues [vermelden alsook al sluiten](https://stackoverflow.com/questions/1687262/link-to-the-issue-number-on-github-within-a-commit-message))
